image: python2.7
git:
  path: github.com/awailly/cis-ubuntu-ansible
notify:
  irc:
    channel: hdbot
    nick: drone-cis
    server: "chat.freenode.net:6667"
    on_started: true
    on_success: true
    on_failure: true
script:
  - sudo apt-get update -qq
  - sudo apt-get install aptitude ufw
  - sudo npm install -g coverage-badge
  - sudo ln -s /usr/bin/env /bin/env
  - cp tests/drone_defaults.yml vars/main.yml
  - pip install ansible
  - echo '[defaults]' > ansible.cfg
  - echo 'roles_path = ../' >> ansible.cfg
  - ansible-playbook -i tests/inventory tests/playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1 > results.txt
  - cat results.txt
  - coverage-badge `cat results.txt | grep ok=.*changed=.*unreachable=.*failed= | awk -F '[= ]+' '{printf("%2.0f", $6/175*100)}'` ./coverage.png
  - ansible-playbook -i tests/inventory tests/playbook.yml --connection=local --sudo -e "pipelining=True" -t level1 > results_indempotence.txt
  - cat results_indempotence.txt
  - cat results_indempotence.txt | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test:pass' && exit 0) || (echo 'Idempotence test:fail' && exit 1)
